(require 'gud)
(setq cmd "battle_svr_2")
(defun debug_battle(&optional program)
  "use shell command to get pids"
  (interactive "sprogram to debug")
  (setq shell_cmd (format "ps -elf |grep %s |grep hrtime | grep -v grep|awk -F ' ' 'END{print $4}'" program))
  (setq pid (string-to-int (shell-command-to-string shell_cmd )))
  (message pid)
  (gdb (format "gdb --annotate=1 %s" program))
  (process-send-string (format "*gud-%s*" program) (format "attach %s\n" pid))
  )
